### ISSUE TITLE
Add Loading Effect Before Getting Response

### ISSUE THREAD

**Issue by LokeshwarPrasad3** [LokeshwarPrasad3/Budgetter-Webapp#25]
### Steps
1. Goto Reports section
2. After a time it get response and show data

## Before Response 
*Need to add loader effect*
![image](https://github.com/user-attachments/assets/5e9802a8-7426-4480-9e29-1faa4fa097a9)

## After Response
![image](https://github.com/user-attachments/assets/5db40636-794f-4f04-adb4-5664f51b6ef7)

### Expected Behavior 
**Add Loader which shows server response is coming**.

**Comment by PerKerK-2003** [comment]
Ok assign me, I will try it

**Comment by lokeshwardewangan** [comment]
Hii @PerKerK-2003 Thanks again for your contribution to this PR 🙌

If you get a moment, please consider giving the repo a ⭐ — it really helps with visibility and growth.

Appreciate your support!
