### ISSUE TITLE
Feat : Add percentage value in legend marker

### ISSUE THREAD

**Issue by LokeshwarPrasad3** [LokeshwarPrasad3/Budgetter-Webapp#34]
### Expected Behavior
In the dashboard section of donut chart
show percentage values in legend marker that how % expenses they spend, this will help to analyze better

![image](https://github.com/user-attachments/assets/d9862bc6-d4ce-46c5-96e5-7848c092fd4e)

**Comment by tkim602** [comment]
hi if it is not already taken, can I work on this issue?

**Comment by starchcode** [comment]
Hi I'd like to take it. can you assign this to me?

**Comment by LokeshwarPrasad3** [comment]
Hii @tkim602 , sorry for late response, i assigned that issue to you.

**Comment by tkim602** [comment]
@LokeshwarPrasad3  I have just created a PR but am not sure this is what you meant. Please let me know if I misunderstood and anything needs to be fixed.

**Comment by lokeshwardewangan** [comment]
Hey @tkim602, thanks again for your contribution here 🙌

@starchcode thanks for showing interest in this earlier as well 🙂

If you get a moment, please consider giving the repo a ⭐ — it really helps with visibility and growth.

Appreciate your support!
